# Developing Dashboards {#dashboards}

This last chapter introduces techniques to create interactive dashboards with the Shiny package. In the previous two case studies you created a slide deck and a report to share the results of your analysis. The RMarkdown language allows you to create static documents that are linked to variable data. While presentations and reports are effective ways to communicate your results, the reader is unable to explore the data. The Shiny package is a powerful extension to the R language that makes it fairly easy to create interactive applications to showcase your analysis.

## Shiny
Working with Shiny is quite different to writing a normal R script. When you run a script, R evaluates each expression in order. Changing a variable does not automatically change the other values that depend on it. In an interactive application we need to have an environment that updates everything as soon as the user changes a value. This behaviour is called reactivity.

## 

## Sharing Dashboards

## Mini Hackathon

