<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Linear Regression | Data Science for Water Professionals - Create Value from Data with the R Language</title>
  <meta name="description" content="Data science course for water management professionals using the R language. This course is developed for water professionals with little to no experience writing code to analyse data." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Linear Regression | Data Science for Water Professionals - Create Value from Data with the R Language" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://lucidmanager.org/r4h2o" />
  <meta property="og:image" content="https://lucidmanager.org/r4h2o/images/r4h2o-cover.jpg" />
  <meta property="og:description" content="Data science course for water management professionals using the R language. This course is developed for water professionals with little to no experience writing code to analyse data." />
  <meta name="github-repo" content="pprevos/r4h2o" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Linear Regression | Data Science for Water Professionals - Create Value from Data with the R Language" />
  
  <meta name="twitter:description" content="Data science course for water management professionals using the R language. This course is developed for water professionals with little to no experience writing code to analyse data." />
  <meta name="twitter:image" content="https://lucidmanager.org/r4h2o/images/r4h2o-cover.jpg" />

<meta name="author" content="Dr Peter Prevos" />


<meta name="date" content="2021-12-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="survey.html"/>
<link rel="next" href="close.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science for Water Professionals</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#continuous-improvement"><i class="fa fa-check"></i>Continuous Improvement</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#prerequisites"><i class="fa fa-check"></i><b>1.2</b> Prerequisites</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#case-study-approach"><i class="fa fa-check"></i><b>1.3</b> Case Study approach</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="introduction.html"><a href="introduction.html#case-study-1-water-quality-regulations"><i class="fa fa-check"></i><b>1.3.1</b> Case Study 1: Water Quality Regulations</a></li>
<li class="chapter" data-level="1.3.2" data-path="introduction.html"><a href="introduction.html#case-study-2-customer-experience"><i class="fa fa-check"></i><b>1.3.2</b> Case Study 2: Customer Experience</a></li>
<li class="chapter" data-level="1.3.3" data-path="introduction.html"><a href="introduction.html#case-study-3-digital-metering-data"><i class="fa fa-check"></i><b>1.3.3</b> Case Study 3: Digital Metering Data</a></li>
<li class="chapter" data-level="1.3.4" data-path="introduction.html"><a href="introduction.html#case-study-4-spatial-analysis"><i class="fa fa-check"></i><b>1.3.4</b> Case Study 4: Spatial Analysis</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#learning-the-r-language"><i class="fa fa-check"></i><b>1.4</b> Learning the R Language</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="datascience.html"><a href="datascience.html"><i class="fa fa-check"></i><b>2</b> Principles of Water Utility Data Science</a>
<ul>
<li class="chapter" data-level="2.1" data-path="datascience.html"><a href="datascience.html#what-is-data-science"><i class="fa fa-check"></i><b>2.1</b> What is data science?</a></li>
<li class="chapter" data-level="2.2" data-path="datascience.html"><a href="datascience.html#the-elements-of-data-science"><i class="fa fa-check"></i><b>2.2</b> The Elements of Data Science</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="datascience.html"><a href="datascience.html#domain-knowledge"><i class="fa fa-check"></i><b>2.2.1</b> Domain Knowledge</a></li>
<li class="chapter" data-level="2.2.2" data-path="datascience.html"><a href="datascience.html#mathematical-knowledge"><i class="fa fa-check"></i><b>2.2.2</b> Mathematical Knowledge</a></li>
<li class="chapter" data-level="2.2.3" data-path="datascience.html"><a href="datascience.html#computer-science"><i class="fa fa-check"></i><b>2.2.3</b> Computer Science</a></li>
<li class="chapter" data-level="2.2.4" data-path="datascience.html"><a href="datascience.html#the-unicorn-data-scientist"><i class="fa fa-check"></i><b>2.2.4</b> The Unicorn Data Scientist?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="datascience.html"><a href="datascience.html#the-water-data-value-chain"><i class="fa fa-check"></i><b>2.3</b> The Water-Data Value Chain</a></li>
<li class="chapter" data-level="2.4" data-path="datascience.html"><a href="datascience.html#data-science-tools"><i class="fa fa-check"></i><b>2.4</b> Data Science Tools</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="datascience.html"><a href="datascience.html#spreadsheets"><i class="fa fa-check"></i><b>2.4.1</b> Spreadsheets</a></li>
<li class="chapter" data-level="2.4.2" data-path="datascience.html"><a href="datascience.html#business-intelligence-systems"><i class="fa fa-check"></i><b>2.4.2</b> Business Intelligence Systems</a></li>
<li class="chapter" data-level="2.4.3" data-path="datascience.html"><a href="datascience.html#data-science-code"><i class="fa fa-check"></i><b>2.4.3</b> Data science code</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="datascience.html"><a href="datascience.html#good-data-science"><i class="fa fa-check"></i><b>2.5</b> Good Data Science</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="datascience.html"><a href="datascience.html#data-science-trivium"><i class="fa fa-check"></i><b>2.5.1</b> Data Science Trivium</a></li>
<li class="chapter" data-level="2.5.2" data-path="datascience.html"><a href="datascience.html#useful-data-science"><i class="fa fa-check"></i><b>2.5.2</b> Useful Data Science</a></li>
<li class="chapter" data-level="2.5.3" data-path="datascience.html"><a href="datascience.html#sound-data-science"><i class="fa fa-check"></i><b>2.5.3</b> Sound Data Science</a></li>
<li class="chapter" data-level="2.5.4" data-path="datascience.html"><a href="datascience.html#aesthetic-data-science"><i class="fa fa-check"></i><b>2.5.4</b> Aesthetic Data Science</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="datascience.html"><a href="datascience.html#further-study"><i class="fa fa-check"></i><b>2.6</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>3</b> Introduction to the R Language</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basics.html"><a href="basics.html#the-r-language"><i class="fa fa-check"></i><b>3.1</b> The R Language</a></li>
<li class="chapter" data-level="3.2" data-path="basics.html"><a href="basics.html#basic-principles-of-programming"><i class="fa fa-check"></i><b>3.2</b> Basic principles of programming</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="basics.html"><a href="basics.html#understanding-computer-code"><i class="fa fa-check"></i><b>3.2.1</b> Understanding computer code</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="basics.html"><a href="basics.html#debugging-code"><i class="fa fa-check"></i><b>3.3</b> Debugging Code</a></li>
<li class="chapter" data-level="3.4" data-path="basics.html"><a href="basics.html#using-r-and-rstudio"><i class="fa fa-check"></i><b>3.4</b> Using R and RStudio</a></li>
<li class="chapter" data-level="3.5" data-path="basics.html"><a href="basics.html#basics-of-the-r-language"><i class="fa fa-check"></i><b>3.5</b> Basics of the R language</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="basics.html"><a href="basics.html#variables"><i class="fa fa-check"></i><b>3.5.1</b> Variables</a></li>
<li class="chapter" data-level="3.5.2" data-path="basics.html"><a href="basics.html#arithmetic"><i class="fa fa-check"></i><b>3.5.2</b> Arithmetic</a></li>
<li class="chapter" data-level="3.5.3" data-path="basics.html"><a href="basics.html#vectors"><i class="fa fa-check"></i><b>3.5.3</b> Vectors</a></li>
<li class="chapter" data-level="3.5.4" data-path="basics.html"><a href="basics.html#basic-plots"><i class="fa fa-check"></i><b>3.5.4</b> Basic plots</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="basics.html"><a href="basics.html#rstudio-scripts-and-projects"><i class="fa fa-check"></i><b>3.6</b> RStudio scripts and projects</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="basics.html"><a href="basics.html#readable-code"><i class="fa fa-check"></i><b>3.6.1</b> Readable Code</a></li>
<li class="chapter" data-level="3.6.2" data-path="basics.html"><a href="basics.html#finding-help"><i class="fa fa-check"></i><b>3.6.2</b> Finding help</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="basics.html"><a href="basics.html#quiz-1-calculating-channel-flows"><i class="fa fa-check"></i><b>3.7</b> Quiz 1: Calculating channel flows</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="basics.html"><a href="basics.html#question-1"><i class="fa fa-check"></i><b>3.7.1</b> Question 1</a></li>
<li class="chapter" data-level="3.7.2" data-path="basics.html"><a href="basics.html#question-2"><i class="fa fa-check"></i><b>3.7.2</b> Question 2</a></li>
<li class="chapter" data-level="3.7.3" data-path="basics.html"><a href="basics.html#question-3"><i class="fa fa-check"></i><b>3.7.3</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="basics.html"><a href="basics.html#further-study-1"><i class="fa fa-check"></i><b>3.8</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>4</b> Exploring Data with the Tidyverse</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tidyverse.html"><a href="tidyverse.html#r-libraries"><i class="fa fa-check"></i><b>4.1</b> R Libraries</a></li>
<li class="chapter" data-level="4.2" data-path="tidyverse.html"><a href="tidyverse.html#introducing-the-tidyverse"><i class="fa fa-check"></i><b>4.2</b> Introducing the Tidyverse</a></li>
<li class="chapter" data-level="4.3" data-path="tidyverse.html"><a href="tidyverse.html#case-study-1"><i class="fa fa-check"></i><b>4.3</b> Case Study 1</a></li>
<li class="chapter" data-level="4.4" data-path="tidyverse.html"><a href="tidyverse.html#exploring-the-case-study-data"><i class="fa fa-check"></i><b>4.4</b> Exploring the Case Study Data</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="tidyverse.html"><a href="tidyverse.html#inspect-the-data"><i class="fa fa-check"></i><b>4.4.1</b> Inspect the data</a></li>
<li class="chapter" data-level="4.4.2" data-path="tidyverse.html"><a href="tidyverse.html#explore-the-content"><i class="fa fa-check"></i><b>4.4.2</b> Explore the content</a></li>
<li class="chapter" data-level="4.4.3" data-path="tidyverse.html"><a href="tidyverse.html#explore-variables"><i class="fa fa-check"></i><b>4.4.3</b> Explore variables</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="tidyverse.html"><a href="tidyverse.html#filtering-data"><i class="fa fa-check"></i><b>4.5</b> Filtering data</a></li>
<li class="chapter" data-level="4.6" data-path="tidyverse.html"><a href="tidyverse.html#counting-results"><i class="fa fa-check"></i><b>4.6</b> Counting results</a></li>
<li class="chapter" data-level="4.7" data-path="tidyverse.html"><a href="tidyverse.html#quiz-2-exploring-water-quality-data"><i class="fa fa-check"></i><b>4.7</b> Quiz 2: Exploring Water Quality Data</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="tidyverse.html"><a href="tidyverse.html#question-1-1"><i class="fa fa-check"></i><b>4.7.1</b> Question 1</a></li>
<li class="chapter" data-level="4.7.2" data-path="tidyverse.html"><a href="tidyverse.html#question-2-1"><i class="fa fa-check"></i><b>4.7.2</b> Question 2</a></li>
<li class="chapter" data-level="4.7.3" data-path="tidyverse.html"><a href="tidyverse.html#question-3-1"><i class="fa fa-check"></i><b>4.7.3</b> Question 3</a></li>
<li class="chapter" data-level="4.7.4" data-path="tidyverse.html"><a href="tidyverse.html#question-4"><i class="fa fa-check"></i><b>4.7.4</b> Question 4</a></li>
<li class="chapter" data-level="4.7.5" data-path="tidyverse.html"><a href="tidyverse.html#question-5"><i class="fa fa-check"></i><b>4.7.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="tidyverse.html"><a href="tidyverse.html#further-study-2"><i class="fa fa-check"></i><b>4.8</b> Further Study</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="tidyverse.html"><a href="tidyverse.html#packages"><i class="fa fa-check"></i><b>4.8.1</b> Packages</a></li>
<li class="chapter" data-level="4.8.2" data-path="tidyverse.html"><a href="tidyverse.html#loading-data"><i class="fa fa-check"></i><b>4.8.2</b> Loading data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="statistics.html"><a href="statistics.html"><i class="fa fa-check"></i><b>5</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="5.1" data-path="statistics.html"><a href="statistics.html#problem-statement"><i class="fa fa-check"></i><b>5.1</b> Problem Statement</a></li>
<li class="chapter" data-level="5.2" data-path="statistics.html"><a href="statistics.html#analyse-the-data"><i class="fa fa-check"></i><b>5.2</b> Analyse the Data</a></li>
<li class="chapter" data-level="5.3" data-path="statistics.html"><a href="statistics.html#calculating-percentiles"><i class="fa fa-check"></i><b>5.3</b> Calculating Percentiles</a></li>
<li class="chapter" data-level="5.4" data-path="statistics.html"><a href="statistics.html#analysing-grouped-data"><i class="fa fa-check"></i><b>5.4</b> Analysing Grouped Data</a></li>
<li class="chapter" data-level="5.5" data-path="statistics.html"><a href="statistics.html#quiz-3-analysing-water-quality-data"><i class="fa fa-check"></i><b>5.5</b> Quiz 3: Analysing Water Quality Data</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="statistics.html"><a href="statistics.html#question-1-2"><i class="fa fa-check"></i><b>5.5.1</b> Question 1</a></li>
<li class="chapter" data-level="5.5.2" data-path="statistics.html"><a href="statistics.html#question-2-2"><i class="fa fa-check"></i><b>5.5.2</b> Question 2</a></li>
<li class="chapter" data-level="5.5.3" data-path="statistics.html"><a href="statistics.html#question-3-2"><i class="fa fa-check"></i><b>5.5.3</b> Question 3</a></li>
<li class="chapter" data-level="5.5.4" data-path="statistics.html"><a href="statistics.html#question-4-1"><i class="fa fa-check"></i><b>5.5.4</b> Question 4</a></li>
<li class="chapter" data-level="5.5.5" data-path="statistics.html"><a href="statistics.html#question-5-1"><i class="fa fa-check"></i><b>5.5.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="statistics.html"><a href="statistics.html#further-study-3"><i class="fa fa-check"></i><b>5.6</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>6</b> Visualising Data with ggplot2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ggplot.html"><a href="ggplot.html#principles-of-visualisation"><i class="fa fa-check"></i><b>6.1</b> Principles of Visualisation</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="ggplot.html"><a href="ggplot.html#the-aesthetics-of-visualising-data"><i class="fa fa-check"></i><b>6.1.1</b> The aesthetics of visualising data</a></li>
<li class="chapter" data-level="6.1.2" data-path="ggplot.html"><a href="ggplot.html#telling-stories"><i class="fa fa-check"></i><b>6.1.2</b> Telling Stories</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ggplot.html"><a href="ggplot.html#visualising-data-with-ggplot"><i class="fa fa-check"></i><b>6.2</b> Visualising data with ggplot</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ggplot.html"><a href="ggplot.html#data-1"><i class="fa fa-check"></i><b>6.2.1</b> Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="ggplot.html"><a href="ggplot.html#aesthetics"><i class="fa fa-check"></i><b>6.2.2</b> Aesthetics</a></li>
<li class="chapter" data-level="6.2.3" data-path="ggplot.html"><a href="ggplot.html#geometries"><i class="fa fa-check"></i><b>6.2.3</b> Geometries</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ggplot.html"><a href="ggplot.html#colour-aesthetics"><i class="fa fa-check"></i><b>6.3</b> Colour Aesthetics</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ggplot.html"><a href="ggplot.html#facets"><i class="fa fa-check"></i><b>6.3.1</b> Facets</a></li>
<li class="chapter" data-level="6.3.2" data-path="ggplot.html"><a href="ggplot.html#statistics-1"><i class="fa fa-check"></i><b>6.3.2</b> Statistics</a></li>
<li class="chapter" data-level="6.3.3" data-path="ggplot.html"><a href="ggplot.html#coordinates"><i class="fa fa-check"></i><b>6.3.3</b> Coordinates</a></li>
<li class="chapter" data-level="6.3.4" data-path="ggplot.html"><a href="ggplot.html#themes"><i class="fa fa-check"></i><b>6.3.4</b> Themes</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ggplot.html"><a href="ggplot.html#sharing-visualisations"><i class="fa fa-check"></i><b>6.4</b> Sharing visualisations</a></li>
<li class="chapter" data-level="6.5" data-path="ggplot.html"><a href="ggplot.html#further-study-4"><i class="fa fa-check"></i><b>6.5</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="dataproducts.html"><a href="dataproducts.html"><i class="fa fa-check"></i><b>7</b> Creating Data Products</a>
<ul>
<li class="chapter" data-level="7.1" data-path="dataproducts.html"><a href="dataproducts.html#data-science-workflow"><i class="fa fa-check"></i><b>7.1</b> Data Science Workflow</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="dataproducts.html"><a href="dataproducts.html#define"><i class="fa fa-check"></i><b>7.1.1</b> Define</a></li>
<li class="chapter" data-level="7.1.2" data-path="dataproducts.html"><a href="dataproducts.html#prepare"><i class="fa fa-check"></i><b>7.1.2</b> Prepare</a></li>
<li class="chapter" data-level="7.1.3" data-path="dataproducts.html"><a href="dataproducts.html#understand"><i class="fa fa-check"></i><b>7.1.3</b> Understand</a></li>
<li class="chapter" data-level="7.1.4" data-path="dataproducts.html"><a href="dataproducts.html#communicate"><i class="fa fa-check"></i><b>7.1.4</b> Communicate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="dataproducts.html"><a href="dataproducts.html#reproducible-and-replicable-research"><i class="fa fa-check"></i><b>7.2</b> Reproducible and Replicable Research</a></li>
<li class="chapter" data-level="7.3" data-path="dataproducts.html"><a href="dataproducts.html#r-markdown"><i class="fa fa-check"></i><b>7.3</b> R-Markdown</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="dataproducts.html"><a href="dataproducts.html#formatting-tables"><i class="fa fa-check"></i><b>7.3.1</b> Formatting tables</a></li>
<li class="chapter" data-level="7.3.2" data-path="dataproducts.html"><a href="dataproducts.html#presenting-numbers"><i class="fa fa-check"></i><b>7.3.2</b> Presenting numbers</a></li>
<li class="chapter" data-level="7.3.3" data-path="dataproducts.html"><a href="dataproducts.html#export-formats"><i class="fa fa-check"></i><b>7.3.3</b> Export formats</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="dataproducts.html"><a href="dataproducts.html#further-study-5"><i class="fa fa-check"></i><b>7.4</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tidyverse.html"><a href="tidyverse.html#cleaning"><i class="fa fa-check"></i><b>8</b> Cleaning Data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="cleaning.html"><a href="cleaning.html"><i class="fa fa-check"></i><b>8.1</b> Case Study 2</a></li>
<li class="chapter" data-level="8.2" data-path="cleaning.html"><a href="cleaning.html#cleaning-data"><i class="fa fa-check"></i><b>8.2</b> Cleaning data</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="cleaning.html"><a href="cleaning.html#load-and-explore-the-data"><i class="fa fa-check"></i><b>8.2.1</b> Load and explore the data</a></li>
<li class="chapter" data-level="8.2.2" data-path="cleaning.html"><a href="cleaning.html#remove-unwanted-responses"><i class="fa fa-check"></i><b>8.2.2</b> Remove unwanted responses</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="cleaning.html"><a href="cleaning.html#joining-data-frames"><i class="fa fa-check"></i><b>8.3</b> Joining data frames</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="cleaning.html"><a href="cleaning.html#select-relevant-variables"><i class="fa fa-check"></i><b>8.3.1</b> Select relevant variables</a></li>
<li class="chapter" data-level="8.3.2" data-path="cleaning.html"><a href="cleaning.html#writedata"><i class="fa fa-check"></i><b>8.3.2</b> Write data to disk</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="cleaning.html"><a href="cleaning.html#simplifying-code-with-data-pipes"><i class="fa fa-check"></i><b>8.4</b> Simplifying Code with Data Pipes</a></li>
<li class="chapter" data-level="8.5" data-path="cleaning.html"><a href="cleaning.html#quiz-4-cleaning-data"><i class="fa fa-check"></i><b>8.5</b> Quiz 4: Cleaning Data</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="cleaning.html"><a href="cleaning.html#question-1-3"><i class="fa fa-check"></i><b>8.5.1</b> Question 1</a></li>
<li class="chapter" data-level="8.5.2" data-path="cleaning.html"><a href="cleaning.html#question-2-3"><i class="fa fa-check"></i><b>8.5.2</b> Question 2</a></li>
<li class="chapter" data-level="8.5.3" data-path="cleaning.html"><a href="cleaning.html#question-3-3"><i class="fa fa-check"></i><b>8.5.3</b> Question 3</a></li>
<li class="chapter" data-level="8.5.4" data-path="cleaning.html"><a href="cleaning.html#question-4-2"><i class="fa fa-check"></i><b>8.5.4</b> Question 4</a></li>
<li class="chapter" data-level="8.5.5" data-path="cleaning.html"><a href="cleaning.html#question-5-2"><i class="fa fa-check"></i><b>8.5.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="cleaning.html"><a href="cleaning.html#further-study-6"><i class="fa fa-check"></i><b>8.6</b> Further Study</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="customers.html"><a href="customers.html"><i class="fa fa-check"></i><b>9</b> Exploring the Customer Experience</a>
<ul>
<li class="chapter" data-level="9.1" data-path="customers.html"><a href="customers.html#measuring-mental-states"><i class="fa fa-check"></i><b>9.1</b> Measuring Mental States</a></li>
<li class="chapter" data-level="9.2" data-path="customers.html"><a href="customers.html#consumer-involvement"><i class="fa fa-check"></i><b>9.2</b> Consumer Involvement</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="customers.html"><a href="customers.html#personal-involvement-inventory"><i class="fa fa-check"></i><b>9.2.1</b> Personal Involvement Inventory</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="customers.html"><a href="customers.html#preparing-the-involvement-data"><i class="fa fa-check"></i><b>9.3</b> Preparing the Involvement Data</a></li>
<li class="chapter" data-level="9.4" data-path="customers.html"><a href="customers.html#tidy-data"><i class="fa fa-check"></i><b>9.4</b> Tidy Data</a></li>
<li class="chapter" data-level="9.5" data-path="customers.html"><a href="customers.html#missing-data"><i class="fa fa-check"></i><b>9.5</b> Missing Data</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="customers.html"><a href="customers.html#imputation"><i class="fa fa-check"></i><b>9.5.1</b> Imputation</a></li>
<li class="chapter" data-level="9.5.2" data-path="customers.html"><a href="customers.html#calculations-with-missing-data"><i class="fa fa-check"></i><b>9.5.2</b> Calculations with missing data</a></li>
<li class="chapter" data-level="9.5.3" data-path="customers.html"><a href="customers.html#explore-the-results"><i class="fa fa-check"></i><b>9.5.3</b> Explore the results</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="customers.html"><a href="customers.html#quiz-5-transforming-data"><i class="fa fa-check"></i><b>9.6</b> Quiz 5: Transforming data</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="customers.html"><a href="customers.html#question-1-4"><i class="fa fa-check"></i><b>9.6.1</b> Question 1</a></li>
<li class="chapter" data-level="9.6.2" data-path="customers.html"><a href="customers.html#question-2-4"><i class="fa fa-check"></i><b>9.6.2</b> Question 2</a></li>
<li class="chapter" data-level="9.6.3" data-path="customers.html"><a href="customers.html#question-3-4"><i class="fa fa-check"></i><b>9.6.3</b> Question 3</a></li>
<li class="chapter" data-level="9.6.4" data-path="customers.html"><a href="customers.html#question-4-3"><i class="fa fa-check"></i><b>9.6.4</b> Question 4</a></li>
<li class="chapter" data-level="9.6.5" data-path="customers.html"><a href="customers.html#question-5-3"><i class="fa fa-check"></i><b>9.6.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="customers.html"><a href="customers.html#further-study-7"><i class="fa fa-check"></i><b>9.7</b> Further Study</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="customers.html"><a href="customers.html#the-dplyr-package"><i class="fa fa-check"></i><b>9.7.1</b> The <em>dplyr</em> package</a></li>
<li class="chapter" data-level="9.7.2" data-path="customers.html"><a href="customers.html#customer-surveys"><i class="fa fa-check"></i><b>9.7.2</b> Customer Surveys</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="survey.html"><a href="survey.html"><i class="fa fa-check"></i><b>10</b> Analysing the customer experience</a>
<ul>
<li class="chapter" data-level="10.1" data-path="survey.html"><a href="survey.html#the-reliability-and-validity-of-survey-results"><i class="fa fa-check"></i><b>10.1</b> The Reliability and Validity of Survey Results</a></li>
<li class="chapter" data-level="10.2" data-path="survey.html"><a href="survey.html#correlations"><i class="fa fa-check"></i><b>10.2</b> Correlations</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="survey.html"><a href="survey.html#visualising-correlation"><i class="fa fa-check"></i><b>10.2.1</b> Visualising correlation</a></li>
<li class="chapter" data-level="10.2.2" data-path="survey.html"><a href="survey.html#statisical-significance"><i class="fa fa-check"></i><b>10.2.2</b> Statisical significance</a></li>
<li class="chapter" data-level="10.2.3" data-path="survey.html"><a href="survey.html#missing-values-in-correlations"><i class="fa fa-check"></i><b>10.2.3</b> Missing values in correlations</a></li>
<li class="chapter" data-level="10.2.4" data-path="survey.html"><a href="survey.html#limitations-of-correlations"><i class="fa fa-check"></i><b>10.2.4</b> Limitations of correlations</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="survey.html"><a href="survey.html#cronbachs-alpha"><i class="fa fa-check"></i><b>10.3</b> Cronbach’s Alpha</a></li>
<li class="chapter" data-level="10.4" data-path="survey.html"><a href="survey.html#hierarchical-clustering-to-assess-validity"><i class="fa fa-check"></i><b>10.4</b> Hierarchical Clustering to assess validity</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="survey.html"><a href="survey.html#clustering-analysis-example"><i class="fa fa-check"></i><b>10.4.1</b> Clustering Analysis Example</a></li>
<li class="chapter" data-level="10.4.2" data-path="survey.html"><a href="survey.html#pre-processing"><i class="fa fa-check"></i><b>10.4.2</b> Pre-processing</a></li>
<li class="chapter" data-level="10.4.3" data-path="survey.html"><a href="survey.html#scaling"><i class="fa fa-check"></i><b>10.4.3</b> Scaling</a></li>
<li class="chapter" data-level="10.4.4" data-path="survey.html"><a href="survey.html#distances"><i class="fa fa-check"></i><b>10.4.4</b> Distances</a></li>
<li class="chapter" data-level="10.4.5" data-path="survey.html"><a href="survey.html#clustering"><i class="fa fa-check"></i><b>10.4.5</b> Clustering</a></li>
<li class="chapter" data-level="10.4.6" data-path="survey.html"><a href="survey.html#interpreting-cluster-analyses"><i class="fa fa-check"></i><b>10.4.6</b> Interpreting Cluster Analyses</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="survey.html"><a href="survey.html#clustering-the-involvement-data"><i class="fa fa-check"></i><b>10.5</b> Clustering the Involvement Data</a></li>
<li class="chapter" data-level="10.6" data-path="survey.html"><a href="survey.html#reviewing-the-personal-involvement-index"><i class="fa fa-check"></i><b>10.6</b> Reviewing the Personal Involvement Index</a></li>
<li class="chapter" data-level="10.7" data-path="survey.html"><a href="survey.html#quiz"><i class="fa fa-check"></i><b>10.7</b> Quiz</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="survey.html"><a href="survey.html#question-1-5"><i class="fa fa-check"></i><b>10.7.1</b> Question 1</a></li>
<li class="chapter" data-level="10.7.2" data-path="survey.html"><a href="survey.html#question-2-5"><i class="fa fa-check"></i><b>10.7.2</b> Question 2</a></li>
<li class="chapter" data-level="10.7.3" data-path="survey.html"><a href="survey.html#question-3-5"><i class="fa fa-check"></i><b>10.7.3</b> Question 3</a></li>
<li class="chapter" data-level="10.7.4" data-path="survey.html"><a href="survey.html#question-4-4"><i class="fa fa-check"></i><b>10.7.4</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="survey.html"><a href="survey.html#further-study-8"><i class="fa fa-check"></i><b>10.8</b> Further study</a>
<ul>
<li class="chapter" data-level="10.8.1" data-path="survey.html"><a href="survey.html#other-techniques"><i class="fa fa-check"></i><b>10.8.1</b> Other techniques</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>11</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="11.1" data-path="linear-regression.html"><a href="linear-regression.html#principles-of-linear-regression"><i class="fa fa-check"></i><b>11.1</b> Principles of Linear Regression</a></li>
<li class="chapter" data-level="11.2" data-path="linear-regression.html"><a href="linear-regression.html#basic-linear-regression-in-r"><i class="fa fa-check"></i><b>11.2</b> Basic Linear Regression in R</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="linear-regression.html"><a href="linear-regression.html#the-linear-model-function"><i class="fa fa-check"></i><b>11.2.1</b> The linear model function</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="linear-regression.html"><a href="linear-regression.html#assessing-linear-relationship-models"><i class="fa fa-check"></i><b>11.3</b> Assessing Linear Relationship Models</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="linear-regression.html"><a href="linear-regression.html#residuals"><i class="fa fa-check"></i><b>11.3.1</b> Residuals</a></li>
<li class="chapter" data-level="11.3.2" data-path="linear-regression.html"><a href="linear-regression.html#coefficients"><i class="fa fa-check"></i><b>11.3.2</b> Coefficients</a></li>
<li class="chapter" data-level="11.3.3" data-path="linear-regression.html"><a href="linear-regression.html#residual-standard-error"><i class="fa fa-check"></i><b>11.3.3</b> Residual Standard Error</a></li>
<li class="chapter" data-level="11.3.4" data-path="linear-regression.html"><a href="linear-regression.html#r-squared"><i class="fa fa-check"></i><b>11.3.4</b> R-Squared</a></li>
<li class="chapter" data-level="11.3.5" data-path="linear-regression.html"><a href="linear-regression.html#f-statistic"><i class="fa fa-check"></i><b>11.3.5</b> F-statistic</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="linear-regression.html"><a href="linear-regression.html#graphical-assessment"><i class="fa fa-check"></i><b>11.4</b> Graphical Assessment</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="linear-regression.html"><a href="linear-regression.html#residuals-vs-fitted"><i class="fa fa-check"></i><b>11.4.1</b> Residuals vs Fitted</a></li>
<li class="chapter" data-level="11.4.2" data-path="linear-regression.html"><a href="linear-regression.html#normal-q-q"><i class="fa fa-check"></i><b>11.4.2</b> Normal Q-Q</a></li>
<li class="chapter" data-level="11.4.3" data-path="linear-regression.html"><a href="linear-regression.html#conclusion"><i class="fa fa-check"></i><b>11.4.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="linear-regression.html"><a href="linear-regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>11.5</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="linear-regression.html"><a href="linear-regression.html#service-quality"><i class="fa fa-check"></i><b>11.5.1</b> Service quality</a></li>
<li class="chapter" data-level="11.5.2" data-path="linear-regression.html"><a href="linear-regression.html#technical-quality"><i class="fa fa-check"></i><b>11.5.2</b> Technical Quality</a></li>
<li class="chapter" data-level="11.5.3" data-path="linear-regression.html"><a href="linear-regression.html#functional-quality"><i class="fa fa-check"></i><b>11.5.3</b> Functional Quality</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="linear-regression.html"><a href="linear-regression.html#further-study-9"><i class="fa fa-check"></i><b>11.6</b> Further study</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="close.html"><a href="close.html"><i class="fa fa-check"></i><b>12</b> In Closing</a>
<ul>
<li class="chapter" data-level="12.1" data-path="close.html"><a href="close.html#searching-for-answers"><i class="fa fa-check"></i><b>12.1</b> Searching for answers</a></li>
<li class="chapter" data-level="12.2" data-path="close.html"><a href="close.html#forums"><i class="fa fa-check"></i><b>12.2</b> Forums</a></li>
<li class="chapter" data-level="12.3" data-path="close.html"><a href="close.html#further-study-10"><i class="fa fa-check"></i><b>12.3</b> Further Study</a></li>
<li class="chapter" data-level="12.4" data-path="close.html"><a href="close.html#thanks"><i class="fa fa-check"></i><b>12.4</b> Thanks</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>13</b> Appendix</a>
<ul>
<li class="chapter" data-level="13.1" data-path="appendix.html"><a href="appendix.html#answers-to-quiz-1"><i class="fa fa-check"></i><b>13.1</b> Answers to Quiz 1</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="appendix.html"><a href="appendix.html#question-1-6"><i class="fa fa-check"></i><b>13.1.1</b> Question 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="appendix.html"><a href="appendix.html#question-2-6"><i class="fa fa-check"></i><b>13.1.2</b> Question 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="appendix.html"><a href="appendix.html#question-3-6"><i class="fa fa-check"></i><b>13.1.3</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="appendix.html"><a href="appendix.html#answers-to-quiz-2"><i class="fa fa-check"></i><b>13.2</b> Answers to Quiz 2</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="appendix.html"><a href="appendix.html#question-1-7"><i class="fa fa-check"></i><b>13.2.1</b> Question 1</a></li>
<li class="chapter" data-level="13.2.2" data-path="appendix.html"><a href="appendix.html#question-2-7"><i class="fa fa-check"></i><b>13.2.2</b> Question 2</a></li>
<li class="chapter" data-level="13.2.3" data-path="appendix.html"><a href="appendix.html#question-3-7"><i class="fa fa-check"></i><b>13.2.3</b> Question 3</a></li>
<li class="chapter" data-level="13.2.4" data-path="appendix.html"><a href="appendix.html#question-4-5"><i class="fa fa-check"></i><b>13.2.4</b> Question 4</a></li>
<li class="chapter" data-level="13.2.5" data-path="appendix.html"><a href="appendix.html#question-5-4"><i class="fa fa-check"></i><b>13.2.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="appendix.html"><a href="appendix.html#answers-to-quiz-3"><i class="fa fa-check"></i><b>13.3</b> Answers to Quiz 3</a></li>
<li class="chapter" data-level="13.4" data-path="appendix.html"><a href="appendix.html#answers-to-quiz-4"><i class="fa fa-check"></i><b>13.4</b> Answers to Quiz 4</a>
<ul>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#question-1-8"><i class="fa fa-check"></i>Question 1</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#question-2-8"><i class="fa fa-check"></i>Question 2</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#question-3-8"><i class="fa fa-check"></i>Question 3</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#question-4-6"><i class="fa fa-check"></i>Question 4</a></li>
<li class="chapter" data-level="" data-path="appendix.html"><a href="appendix.html#question-5-5"><i class="fa fa-check"></i>Question 5</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://peterprevos.com/" target="blank">Dr Peter Prevos</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for Water Professionals - Create Value from Data with the R Language</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression" class="section level1" number="11">
<h1><span class="header-section-number">Chapter 11</span> Linear Regression</h1>
<p>The previous two chapters demonstrated some of the basic principles of administering and analysing customer survey data. Hierarchical clustering reduces the number of dimensions in the involvement data and informally assesses its validity and reliability. This chapter uses these clustered results to investigate relationships between the various parts of the survey results.</p>
<p>Regression analysis is one of the most common method to investigate relationships between variables. Understanding and using linear regression is a first step towards predictive analysis and machine learning. This chapter investigates possible linear relationships between the responses in the customer survey and uses these results to explain the theory and practice of building and assessing linear models.</p>
<p>The learning objectives for this chapter are:</p>
<ul>
<li>Understand the principles of linear regression</li>
<li>Perform a linear regression of the customer survey data</li>
<li>Assess the significance of a linear regression</li>
</ul>
<div id="principles-of-linear-regression" class="section level2" number="11.1">
<h2><span class="header-section-number">11.1</span> Principles of Linear Regression</h2>
<p>A regression analysis finds the best possible relationship between two or more variables. The result of this analysis is a function that describes this relationship, which can be used to predict unobserved events. Through regression, the computer learns from existing observations in order to predict future events.</p>
<p>Dependent and independent variables relate to experiments where researchers manipulate the independent variables to study their effect on the dependent variable. In an urban water context, a common dependent variable is water consumption and independent variables are parameters such as household size, outdoor temperature and so on. Lets look at a simple simulated example. Figure <a href="linear-regression.html#fig:lm">11.1</a> shows a random set of data points (<span class="math inline">\(x,y\)</span>).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:lm"></span>
<img src="r4h2o_files/figure-html/lm-1.png" alt="Linear regression example." width="60%" />
<p class="caption">
Figure 11.1: Linear regression example.
</p>
</div>
<p>The purpose of regression analysis is to find the line of best fit through the points (the solid blue line). The best fit is defined as the line that minimises error, indicated by the red dotted lines. The error <span class="math inline">\(\epsilon\)</span>, also called residual, is the absolute difference between the measured value for <span class="math inline">\(y\)</span> and the predicted value <span class="math inline">\(\hat{y}\)</span> (pronounced <span class="math inline">\(y\)</span>-hat).</p>
<p><span class="math display">\[\hat{y} = \beta_0 + \beta_1 x + \epsilon\]</span></p>
<p>The predicted value <span class="math inline">\(\hat{y}\)</span> is <span class="math inline">\(\beta_0 + \beta_1 x\)</span> plus an error <span class="math inline">\(\epsilon\)</span>. The easiest method to determine the parameters for this line is <a href="https://en.wikipedia.org/wiki/Ordinary_least_squares" title="Wikipedia">Ordinary Least Squares</a> (OLS).</p>
<p>The first step to build the model is to determine the squared deviation from the mean (<span class="math inline">\(\bar{y}\)</span>, pronounced <span class="math inline">\(y\)</span>-bar) of the <span class="math inline">\(n\)</span> observations (<span class="math inline">\(y_i\)</span>):</p>
<p><span class="math display">\[SS_{mean} = \sum_{i=1}^{i=n}{(y_i-\bar{y})^2}\]</span>
The Sum of Squares (<span class="math inline">\(SS_{fit}\)</span>) of the difference between the predicted (<span class="math inline">\(\hat{y}\)</span>) and the observed values <span class="math inline">\(y_i\)</span> indicates how well the predicted results fit the observations:</p>
<p><span class="math display">\[SS_{fit} = \sum_{i=1}^{i=n}{(y_i-\hat{y})^2}\]</span></p>
<p>You can visualise this formula by drawing a horizontal line through the observations (figure <a href="linear-regression.html#fig:ols">11.2</a>). To find the best fit, rotate this line around the centre of the point cloud (<span class="math inline">\(\bar{x}, \bar{y}\)</span>), until you find the lowest sum of squares (<span class="math inline">\(SS\)</span>). Figure <a href="linear-regression.html#fig:ols">11.2</a> visualises the residuals for the average <span class="math inline">\(y\)</span> value, two rotations and the model with the lowest <span class="math inline">\(SS\)</span> value.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ols"></span>
<img src="r4h2o_files/figure-html/ols-1.png" alt="Ordinary Minimum Least Squares method." width="80%" />
<p class="caption">
Figure 11.2: Ordinary Minimum Least Squares method.
</p>
</div>
<p>Deriving the method to determine the line of best fit is a matter of complex algebra. Suffice to say that the slope of the line relates to the correlation and the standard deviations of the observed variables. We can determine the linear parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> with the following formulas:</p>
<p><span class="math display">\[\beta_1 = cor(y,x) \frac{sd(y)}{sd(x)}\]</span>
<span class="math display">\[\beta_0 = \bar{y} - \beta_1  \bar{x}\]</span></p>
<p>The data in table <a href="#tab:error"><strong>??</strong></a> is stored in the <code>d</code> variable. We can use basic R functions to calculate the parameters for the regression line.</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="linear-regression.html#cb196-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">cor</span>(d<span class="sc">$</span>y, d<span class="sc">$</span>x) <span class="sc">*</span> <span class="fu">sd</span>(d<span class="sc">$</span>y) <span class="sc">/</span> <span class="fu">sd</span>(d<span class="sc">$</span>x)</span>
<span id="cb196-2"><a href="linear-regression.html#cb196-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">mean</span>(d<span class="sc">$</span>y) <span class="sc">-</span> a <span class="sc">*</span> <span class="fu">mean</span>(d<span class="sc">$</span>x)</span>
<span id="cb196-3"><a href="linear-regression.html#cb196-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;a = &quot;</span>, <span class="fu">round</span>(a, <span class="dv">3</span>), <span class="st">&quot;; b = &quot;</span>, <span class="fu">round</span>(b, <span class="dv">3</span>))</span></code></pre></div>
<pre><code>## [1] &quot;a =  0.966 ; b =  9.851&quot;</code></pre>
<p>The <code>paste()</code> function paste strings and variables, which is often useful in literate programming.</p>
<p>The closer the residuals are to zero, the better the fit and the more reliable any prediction will be.</p>
<p>The R language has extensive capabilities to build and assess linear models, which are discussed in some detail below.</p>
</div>
<div id="basic-linear-regression-in-r" class="section level2" number="11.2">
<h2><span class="header-section-number">11.2</span> Basic Linear Regression in R</h2>
<p>We can put this algebra aside as the R language has a versatile linear modelling function to help you analyse observations and assess the reliability of your model. Lets use some of the data of Case Study 2.</p>
<p>The survey contains data about two customer characteristics and how they perceive the quality of the service.</p>
<p>Customers were asked to indicate whether they struggle to pay their water bills when they fall due. This question used a seven-point Likert scale from “Strongly Disagree” to “Strongly Agree”, which we can code 1–7.</p>
<p>The second question asked customers to indicate the frequency at which they contact their utility for support, also using a seven-point Likert scale:</p>
<ol style="list-style-type: decimal">
<li>Never</li>
<li>Less than once a month</li>
<li>Once a month</li>
<li>2–3 Times a month</li>
<li>Once a week</li>
<li>2–3 Times a week</li>
<li>Daily</li>
</ol>
<p>Perhaps we can use this data to predict whether a customer might experience hardship by looking at their contact frequency. The hypothesis being that customers who suffer from financial hardship will contact the utility frequently might than those who easily pat their bills.</p>
<p>To analyse this hypothesised relationship, we use the cleaned survey data prepared in <a href="tidyverse.html#cleaning">chapter 8</a>.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="linear-regression.html#cb198-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb198-2"><a href="linear-regression.html#cb198-2" aria-hidden="true" tabindex="-1"></a>customers <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;casestudy2/customer_survey_clean.csv&quot;</span>)</span></code></pre></div>
<blockquote>
<p><strong>Practice Task</strong>: Correlation is closely associated with linear regression. What is the correlation between the level of hardship and the contact frequency in the customers data (beware of the missing values)?</p>
</blockquote>
<p>Answer:</p>
<p>The <code>use</code> parameter in the <code>cor()</code> function specified that we should only use observations where a pair of numbers is available. Read the help file for the correlation function for details of other methods to work with missing data.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="linear-regression.html#cb199-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(customers<span class="sc">$</span>contact, customers<span class="sc">$</span>hardship, <span class="at">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.482781</code></pre>
<p>First step in our workflow is to visualise the data. Because Likert-scale data only contains the integers 1–7, we have an overplotting issue. In the previous chapter we solved it with some random jitter (figure <a href="survey.html#fig:jitter">10.2</a>).</p>
<p>Another method to manage overplotting is to count the frequency of each combination of <code>hardship</code> and <code>contact</code> and relate the size of the point to the frequency (figure <a href="linear-regression.html#fig:fcmodel">11.3</a>). The <code>scale_size()</code> function scales the size of the points by sizing the area of the point to the frequency.</p>
<p>The smoothing layer draws a linear regression model. We need to tell it to use the original data and not the frequency table generated in the first line. This graph is an example of how layers in <em>ggplot2</em> can use different data sets by using <code>data =</code> and <code>aes()</code> in the geometry function.</p>
<p>The regression line from the smoothing geometry suggests a linear relationship between the two variables. The grey band behind the regression line is the 95<sup>th</sup> percentile confidence interval, which is discussed in more detail below.</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="linear-regression.html#cb201-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(customers, hardship, contact) <span class="sc">%&gt;%</span> </span>
<span id="cb201-2"><a href="linear-regression.html#cb201-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb201-3"><a href="linear-regression.html#cb201-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(contact, hardship, <span class="at">size =</span> n), <span class="at">col =</span> <span class="st">&quot;darkgrey&quot;</span>) <span class="sc">+</span> </span>
<span id="cb201-4"><a href="linear-regression.html#cb201-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span> customers, <span class="fu">aes</span>(contact, hardship), <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span> </span>
<span id="cb201-5"><a href="linear-regression.html#cb201-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size</span>(<span class="at">guide =</span> <span class="st">&quot;none&quot;</span>, <span class="at">range =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>)) <span class="sc">+</span> </span>
<span id="cb201-6"><a href="linear-regression.html#cb201-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Gormsey Customer Survey&quot;</span>,</span>
<span id="cb201-7"><a href="linear-regression.html#cb201-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Contact frequency&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Financial hardship&quot;</span>) <span class="sc">+</span> </span>
<span id="cb201-8"><a href="linear-regression.html#cb201-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:fcmodel"></span>
<img src="r4h2o_files/figure-html/fcmodel-1.png" alt="Linear regression between financial hardship and contact frequency." width="80%" />
<p class="caption">
Figure 11.3: Linear regression between financial hardship and contact frequency.
</p>
</div>
<p>Visualising the relationships between variables is extremely important, as previously shown in figure <a href="dataproducts.html#fig:datasaurus">7.2</a>. The original idea of various data sets with similar summary statistics is by statistician <a href="https://en.wikipedia.org/wiki/Anscombe%27s_quartet" title="Wikipedia">Francis Anscombe</a>. He devised four data sets, shown in figure <a href="linear-regression.html#fig:anscombe">11.4</a> that have the same mean values, sample variance, correlation and regression line. Visualising these sets shows, however, how different they are.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:anscombe"></span>
<img src="r4h2o_files/figure-html/anscombe-1.png" alt="Anscombe's Quartet" width="80%" />
<p class="caption">
Figure 11.4: Anscombe’s Quartet
</p>
</div>
<p>The second set clearly should not be modelled with a liner relationship. The third and fourth set suffer from outliers in the observations that skew the results.</p>
<p>To explore this data, use:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="linear-regression.html#cb202-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(anscombe)</span>
<span id="cb202-2"><a href="linear-regression.html#cb202-2" aria-hidden="true" tabindex="-1"></a>anscombe</span></code></pre></div>
<div id="the-linear-model-function" class="section level3" number="11.2.1">
<h3><span class="header-section-number">11.2.1</span> The linear model function</h3>
<p>The <code>lm()</code> function performs linear regression models. The output of the function is a list, just like the clustering method in the previous chapter. The linear modelling function in the R base library provides detailed information about the analysis.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="linear-regression.html#cb203-1" aria-hidden="true" tabindex="-1"></a>cont_hard <span class="ot">&lt;-</span> customers <span class="sc">%&gt;%</span> </span>
<span id="cb203-2"><a href="linear-regression.html#cb203-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(id, contact, hardship) <span class="sc">%&gt;%</span> </span>
<span id="cb203-3"><a href="linear-regression.html#cb203-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(contact) <span class="sc">|</span> <span class="sc">!</span><span class="fu">is.na</span>(hardship))</span>
<span id="cb203-4"><a href="linear-regression.html#cb203-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb203-5"><a href="linear-regression.html#cb203-5" aria-hidden="true" tabindex="-1"></a>hc_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(hardship <span class="sc">~</span> contact, <span class="at">data =</span> cont_hard)</span></code></pre></div>
<p>The <code>lm()</code> function uses the formula notation common in R data models. You need to read this as: the linear model (<code>lm</code>) of <code>hardship</code> predicted by (<code>~</code>) <code>contact</code> from the <code>customers</code> data frame.</p>
<p>Printing the results to the console shows the main results. The intercept value <span class="math inline">\(\beta_0\)</span> and the regression coefficient <span class="math inline">\(\beta_1\)</span> for the <code>contact</code> variable.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="linear-regression.html#cb204-1" aria-hidden="true" tabindex="-1"></a>hc_model</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hardship ~ contact, data = cont_hard)
## 
## Coefficients:
## (Intercept)      contact  
##       1.365        0.705</code></pre>
<p>This formula seems to suggest that customers who contact the utility more often tend to experience a higher level of hardship. While this conclusion is intuitively correct, are we mathematically justified to accept this relationship?</p>
</div>
</div>
<div id="assessing-linear-relationship-models" class="section level2" number="11.3">
<h2><span class="header-section-number">11.3</span> Assessing Linear Relationship Models</h2>
<p>Linear model list variables in R contain a lot fo diagnostic information about the analysis. The <code>hc_model</code> is a list, just like we saw with the hierarchical clustering, with nine variables.</p>
<p>We can delve deeper into the analysis with the <code>summary()</code> function.</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="linear-regression.html#cb206-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hc_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = hardship ~ contact, data = cont_hard)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -5.302 -1.071 -0.776  1.224  4.929 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   1.3654     0.1310    10.4   &lt;2e-16 ***
## contact       0.7052     0.0615    11.5   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.62 on 433 degrees of freedom
## Multiple R-squared:  0.233,  Adjusted R-squared:  0.231 
## F-statistic:  132 on 1 and 433 DF,  p-value: &lt;2e-16</code></pre>
<p>This summary provides a wealth of information about the analysis, the function call, the residuals, the coefficients and overall significance of the model.</p>
<p>You can access the individual parts of the list, for show the coefficients with <code>coef(hc_model)</code> or <code>hc_model$coefficients</code>.</p>
<blockquote>
<p>Inspect the various variables of the <code>hc_model</code> list. Read the help file of the <code>lm()</code> function for details.</p>
</blockquote>
<div id="residuals" class="section level3" number="11.3.1">
<h3><span class="header-section-number">11.3.1</span> Residuals</h3>
<p>The first bit of information after the function call shows a summary of the residuals. You can calculate these residuals and compare them with the model output, as shown in <a href="#tab:error"><strong>??</strong></a>.</p>
<p>The <code>predict()</code> function uses the output of the <code>lm()</code> function to calculate the predicted values. The code below calculates the residuals as a demonstration, but they are also stored in the <code>hc_model$residuals</code> variable in the model. This output shows that the calculated residuals are the same as the ones in the <code>hc_model</code> list.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="linear-regression.html#cb208-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">contact =</span> cont_hard<span class="sc">$</span>contact,</span>
<span id="cb208-2"><a href="linear-regression.html#cb208-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">hardship =</span> cont_hard<span class="sc">$</span>hardship,</span>
<span id="cb208-3"><a href="linear-regression.html#cb208-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">prediction =</span> <span class="fu">predict</span>(hc_model),</span>
<span id="cb208-4"><a href="linear-regression.html#cb208-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">res_calc =</span> hardship <span class="sc">-</span> prediction,</span>
<span id="cb208-5"><a href="linear-regression.html#cb208-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">res_lm =</span> hc_model<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## # A tibble: 435 × 5
##    contact hardship prediction res_calc  res_lm
##      &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1       2        1       2.78  -1.78   -1.78  
##  2       7        7       6.30   0.698   0.698 
##  3       2        5       2.78   2.22    2.22  
##  4       1        1       2.07  -1.07   -1.07  
##  5       1        2       2.07  -0.0706 -0.0706
##  6       1        1       2.07  -1.07   -1.07  
##  7       1        4       2.07   1.93    1.93  
##  8       1        5       2.07   2.93    2.93  
##  9       4        4       4.19  -0.186  -0.186 
## 10       1        2       2.07  -0.0706 -0.0706
## # … with 425 more rows</code></pre>
<p>One of the assumptions for hypothesis testing is that errors follow a normal distribution and so should the residuals. The residual summary statistics gives information about the symmetry of the residual distribution.</p>
<p>The median should be zero because the mean of the residuals is zero by definition. Also, the first and third quartile (<code>1Q</code> and <code>3Q</code>) should equal under a normal distribution. The maximum and minimum values should also have a similar magnitude.</p>
<blockquote>
<p><strong>Practice Task</strong>: Visualise the residuals as a histogram with the <code>hist()</code> function. Does it look like a normal distribution?</p>
</blockquote>
<p>Answer:</p>
<p>Using the built-in <code>hist()</code> function is quicker than the more formal ggplot version, whcih require sthat you first create a data frame.</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="linear-regression.html#cb210-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">residuals</span>(hc_model))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-119"></span>
<img src="r4h2o_files/figure-html/unnamed-chunk-119-1.png" alt="Histogram of residuals." width="80%" />
<p class="caption">
Figure 11.5: Histogram of residuals.
</p>
</div>
<p>Violation of these symmetries either indicates that the model does not fit the observation, or that there are outliers that skew the data.</p>
<p>Looking at numbers or a histogram is an informal method to test a distribution for normality. You can test a vector for normality with the <a href="https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test" title="Wikipedia">Shapiro-Wilk normality test</a>.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="linear-regression.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(hc_model<span class="sc">$</span>residuals)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  hc_model$residuals
## W = 0.9035, p-value = 5.55e-16</code></pre>
<p>The results of this test indicate that we can assume the residuals to be normally distributed because the <span class="math inline">\(p\)</span>-value is close to zero, which means that the likelihood that this sample of residuals was <em>not</em> derived from a normally-distributed population is close to zero.</p>
</div>
<div id="coefficients" class="section level3" number="11.3.2">
<h3><span class="header-section-number">11.3.2</span> Coefficients</h3>
<p>The next part of the summary provides information about the estimated regression coefficients, their standard errors, <span class="math inline">\(t\)</span>-statistics, and <span class="math inline">\(p\)</span>-values.</p>
<p>The estimated coefficients express a formulas we saw in the previous section. The intercept is essentially the predicted value when the regressor is zero. You can also extract the coefficients with the <code>coef()</code> function, which results in a named vector with two elements:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="linear-regression.html#cb213-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(hc_model)</span></code></pre></div>
<pre><code>## (Intercept)     contact 
##    1.365373    0.705178</code></pre>
<p>The standard error of the coefficients is an estimate of their standard deviation. This number expresses the uncertainty in the estimated coefficient. You can use the standard error to construct confidence intervals.</p>
<p>In linear regression, the Null-Hypothesis (<span class="math inline">\(H_0\)</span>) is that the beta coefficients associated with the variables is equal to zero. The alternate hypothesis (<span class="math inline">\(H_1\)</span>) is that the coefficients are not equal to zero. If the Null-Hypothesis is refuted, then there exists a relationship between the independent and the dependent variables.</p>
<p>The starts <code>***</code> behind the probabilities indicate their significance, the more stars, the higher the significance.</p>
<p>The <span class="math inline">\(t\)</span>-value is derived from the regression coefficient divided by the standard error. Thus, the greater the standard error, the higher the <span class="math inline">\(t\)</span>-value. In our example, the coefficients are at least ten standard errors away from zero.</p>
<p>The <code>Pr(&gt;|t|)</code> column shows the probability that the Null-Hypothesis is valid. The closer this value is to zero, the better. In social sciences, a limit of 0.05 is often accepted. The limit you are willing to accept as significant depends on the importance of the conclusion you draw from this number.</p>
</div>
<div id="residual-standard-error" class="section level3" number="11.3.3">
<h3><span class="header-section-number">11.3.3</span> Residual Standard Error</h3>
<p>The residual standard error is a measure of how well the model fits the data. This value is the average sum of squares discussed above. The closer this value is to zero, the better the model fits the data.</p>
<p>The degrees of freedom relates to the number of observations and the number of regressors. In a model with only two observations, there are zero degrees of freedom because there is only one line that you can draw through these lines. The degreees of freedom for a regression with one parameter, the degrees of freedom <span class="math inline">\(df=n-2\)</span>. In our case study we have 435 rows of data and one regressor (<code>contact</code>), so <span class="math inline">\(df = 433\)</span>.</p>
</div>
<div id="r-squared" class="section level3" number="11.3.4">
<h3><span class="header-section-number">11.3.4</span> R-Squared</h3>
<p>The <span class="math inline">\(R^2\)</span> value expresses the proportion of the variance in the observations that the model explains. In the case study, the model explains 23% of the variance.</p>
<p>This result means that the model only a small portion of the variance in the data. This low value does not mean that there is no relationship between these variables. More than likely, there are other variables, such as average debt or time to pay a bill, that need to be used to predict hardship status.</p>
<p>You can extract the <span class="math inline">\(R^2\)</span> value from the summary list by calling the <code>r.squared</code> variable.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="linear-regression.html#cb215-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hc_model)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.233078</code></pre>
<p>To calculate <span class="math inline">\(R^2\)</span> you need the variance of a set of observations, which is the average of the sum of squares:</p>
<p><span class="math display">\[var = \frac{1}{n} \sum_{i=1}^{n}(y - \hat{y})^2\]</span></p>
<p>The proportion of variance explained by the linear model is the proportion of the difference between variance of the fitted model and the variance from the mean, divided by the variance from the mean.</p>
<p><span class="math display">\[R^2 = \frac{var_{fit} - var_{mean}}{var_{mean}}\]</span></p>
<p>If the residuals of the fitted valued are zero, then the value for <span class="math inline">\(R^2\)</span> is one.</p>
<p>The adjusted <span class="math inline">\(R^2\)</span> is corrected for the degrees of freedom of the model and should be used in reporting and analysis.</p>
<p>The <span class="math inline">\(R^2\)</span> value should be interpreted with care. It can be manipulated by reducing the degrees of freedom. As shown in the example, a low value does not necessarily mean that there is no relationship, but it could be a sign that the model needs to be enhanced with additional predictors.</p>
</div>
<div id="f-statistic" class="section level3" number="11.3.5">
<h3><span class="header-section-number">11.3.5</span> F-statistic</h3>
<p>The F statistic expresses the ratio between the amount of variance from the mean and the amount of variance</p>
<p><span class="math display">\[F = \frac{var_{mean}}{var_{fit}} df\]</span></p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="linear-regression.html#cb217-1" aria-hidden="true" tabindex="-1"></a>hc_model_summary <span class="ot">&lt;-</span> <span class="fu">summary</span>(hc_model)</span>
<span id="cb217-2"><a href="linear-regression.html#cb217-2" aria-hidden="true" tabindex="-1"></a>hc_model_summary<span class="sc">$</span>fstatistic</span></code></pre></div>
<pre><code>##   value   numdf   dendf 
## 131.595   1.000 433.000</code></pre>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="linear-regression.html#cb219-1" aria-hidden="true" tabindex="-1"></a>ssfit <span class="ot">&lt;-</span> <span class="fu">sum</span>(hc_model<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb219-2"><a href="linear-regression.html#cb219-2" aria-hidden="true" tabindex="-1"></a>ssmean <span class="ot">&lt;-</span> <span class="fu">sum</span>((cont_hard<span class="sc">$</span>hardship <span class="sc">-</span> <span class="fu">mean</span>(cont_hard<span class="sc">$</span>hardship))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb219-3"><a href="linear-regression.html#cb219-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">nrow</span>(cont_hard) <span class="sc">-</span> <span class="dv">2</span></span>
<span id="cb219-4"><a href="linear-regression.html#cb219-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-5"><a href="linear-regression.html#cb219-5" aria-hidden="true" tabindex="-1"></a>F <span class="ot">&lt;-</span> (ssmean <span class="sc">-</span> ssfit) <span class="sc">/</span> (ssfit) <span class="sc">*</span> df</span>
<span id="cb219-6"><a href="linear-regression.html#cb219-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb219-7"><a href="linear-regression.html#cb219-7" aria-hidden="true" tabindex="-1"></a>F</span></code></pre></div>
<pre><code>## [1] 131.595</code></pre>
<p>TO BE COMPLETED</p>
</div>
</div>
<div id="graphical-assessment" class="section level2" number="11.4">
<h2><span class="header-section-number">11.4</span> Graphical Assessment</h2>
<p>Plotting a linear model list results in four plots of the residuals (Figure <a href="linear-regression.html#fig:resid">11.6</a>). When you plot them in the console, you need to hit enter to view the next graph. The first line splits the plot screen in 2 rows and 2 columns. Note that this does not work when you use ggplot. The <code>pch</code>, <code>col</code> and <code>cex</code> options change the shape, colour and size of the data points.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="linear-regression.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb221-2"><a href="linear-regression.html#cb221-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hc_model, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">cex =</span> .<span class="dv">5</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:resid"></span>
<img src="r4h2o_files/figure-html/resid-1.png" alt="Analysis of the linear model residuals." width="100%" />
<p class="caption">
Figure 11.6: Analysis of the linear model residuals.
</p>
</div>
<div id="residuals-vs-fitted" class="section level3" number="11.4.1">
<h3><span class="header-section-number">11.4.1</span> Residuals vs Fitted</h3>
<p>The first plot determines if the residuals exhibit non-linear patterns. The red line should be roughly horizontal, which indicates that a linear model is suitable.</p>
<p>Heteroscedasticity</p>
</div>
<div id="normal-q-q" class="section level3" number="11.4.2">
<h3><span class="header-section-number">11.4.2</span> Normal Q-Q</h3>
<p>The second plot tests the residuals for normality. The dotted straight line are the theoretical quantiles of a normal distribution</p>
<p>If the residuals would not follow a normal distribution, then you could try transforming your data. You could, for example convert one or two variables to a log or square root scale and recast the model.</p>
<div id="scale-location" class="section level4" number="11.4.2.1">
<h4><span class="header-section-number">11.4.2.1</span> Scale-Location</h4>
</div>
<div id="residuals-vs-leverage" class="section level4" number="11.4.2.2">
<h4><span class="header-section-number">11.4.2.2</span> Residuals vs Leverage</h4>
</div>
</div>
<div id="conclusion" class="section level3" number="11.4.3">
<h3><span class="header-section-number">11.4.3</span> Conclusion</h3>
<p>Although we are justified to conclude that there is a positive relationship between contact frequency and hardship, this model is obviously to crude to draw conclusions about the customers financial situation merely based on their contact frequency.</p>
</div>
</div>
<div id="multiple-linear-regression" class="section level2" number="11.5">
<h2><span class="header-section-number">11.5</span> Multiple Linear Regression</h2>
<div id="service-quality" class="section level3" number="11.5.1">
<h3><span class="header-section-number">11.5.1</span> Service quality</h3>
<p>Service quality is a construct that describes how customers perceive a service. Many statistically validated survey tools exist to measure service quality. The most well-known and oldest method is SERVQUAL. This is a tool that consists of over twenty items were customers provide insight into their views on a range of aspects of service quality.</p>
<p>The questions in this customer survey were used to develop a service quality measurement tool for tap water called SERVAQUA. This tool consists of 18 questions, which were measured using a seven-point Likert scale from “Strongly Disagree” to “Strongly Agree”. The items were presented in random order.</p>
<p>The survey looks at how customers view core and supplementary services. The core service of a water utility is obviously the water it supplies. The supplementary services relate to providing customers with assistance when they need to pay bills, have enquiries or have problems.</p>
<p>The core services of water utilities are homogeneous because the physical quality can be controlled at a high level of reliability through technology. The supplementary services are much more subject to variability due to the higher level of interaction between employees and customers. Whereas the core service is undifferentiated with no possibility of customisation, supplementary services need to meet the individual requirements of the customer. When supplementary services are required, the otherwise anonymous customer that is served at arm’s length develops a direct relationship with the service provider.</p>
<p>The core service of water is expressed in questions about the technical quality of the water, and the supplementary services relate to the functional quality of tap water services.</p>
</div>
<div id="technical-quality" class="section level3" number="11.5.2">
<h3><span class="header-section-number">11.5.2</span> Technical Quality</h3>
<p>The technical quality dimension was measured using five questions. The technical quality items are formulated in absolute terms to ensure that the highest score entails a perfect level of service. Based on these considerations, the following five-item instrument was used:</p>
<ul>
<li>Tap water is available whenever I need it.</li>
<li>My tap water is always safe to drink.</li>
<li>My tap water is always visually appealing.</li>
<li>My tap water always has a pleasant taste.</li>
<li>My tap water always has sufficient pressure.</li>
</ul>
</div>
<div id="functional-quality" class="section level3" number="11.5.3">
<h3><span class="header-section-number">11.5.3</span> Functional Quality</h3>
<p>The survey includes 13 functional quality items that measure the non-physical aspects of customer service:</p>
<ul>
<li>My water bills are always accurate.</li>
<li>The services provided by my water utility are reliable.</li>
<li>My water utility always provides good customer service.</li>
<li>I can always depend on the services of my water utility.</li>
<li>Employees of my water utility have the knowledge to answer my questions.</li>
<li>My water utility consistently provides the services they promise.</li>
<li>Employees in my water utility give me prompt service.</li>
<li>When I have problems, my water utility is sympathetic and understanding.</li>
<li>My water utility has my best interests at heart.</li>
<li>Employees of my water utility are always willing to help me.</li>
<li>My water bills are easy to understand.</li>
<li>Employees of my water utility are consistently polite.</li>
<li>My water utility provides me with sufficient information.</li>
</ul>
<p>This survey tool was validated using structural equation modelling. You can read about the detailed analysis of this data and the SERVQUAL model in <a href="http://hdl.handle.net/1959.9/561679">The Invisible Water Utility</a> dissertation. The International Water Association has published a less-mathematical version of this research in the book <em>Customer Experience Management for Water Utilities</em>.</p>
</div>
</div>
<div id="further-study-9" class="section level2" number="11.6">
<h2><span class="header-section-number">11.6</span> Further study</h2>
<p>More advanced analysis of these constructs would require sohpisticated confirmatory factor analysis. This methods analyses networks of causal relationships and their interactions.</p>
<p><a href="https://leanpub.com/regmods" class="uri">https://leanpub.com/regmods</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survey.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="close.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/pprevos/r4h2o/edit/master/11_regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/pprevos/r4h2o/r4h2o-book/blob/master/11_regression.Rmd",
"text": null
},
"download": ["r4h2o.pdf", "r4h2o.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
